[[DtCI_ch09]]

== Trees

Trees is a concept that can make some coder's heads spin; especially those who did not go through a computer science program.  
To some extent I think the reason why is that trees (and graphs, which we'll cover in the next chapter) are usually introduced in the context of other courses a future programmer might be taking that involves mathematical or set-theory-like definitions.

Given how useful trees are, and the extent to which they can separate the sheep from the wolves in the programming world, I'm taking it as a personal challenge to make trees accessible in this chapter.

=== Trees Definition

We've already come across trees in two different contexts in this book.
I discussed them in chapter 4 when I introduced the binary search algorithm, and I discussed them in 7 in the context of heaps.

=== Building Intuition: What are trees used for?

An example of a tree you use every single day, and you might even be using it right now, is the document object model (DOM) in your web browser.
The DOM represents every single element on an HTML page as a node in a tree.
If you've done any HTML programming this will make intuitive sense to you.
For instance, in HTML every tag that is "opened" must eventually be "closed" with a corresponding tag.  
That's the tree structure in a nutshell.

PICTURE OF DOM AS TREE TK


=== Reasoning about Trees

A tree most people are familiar with is a tournament bracket.  
A tournament bracket lists all of the teams (or players) in a tournament and their match-ups.
When each round is completed the winner moves on the the next round.

// IMAGE OF TOURNAMENT BRACKET TK

The reason I mention a tournament bracket is because it makes it easy to see the relationship between trees and logarithms.
Assuming the tournament is "single-elimination", meaning each team has to win its match or be eliminated, the number of rounds in the tournament is equal to the logarithm of the number of teams.  

If you take the "sweet sixteen" round of a tournament, a round where there are 16 teams left, the logarithm of 16 is 4.
This means there are 4 rounds left in the tournament.
This is illustrated by following the path from the "Happy Crocodiles" all the way to the championship game.

// IMAGE OF TOURNAMENT WITH HIGHLIGHTED PATH TK

=== Tree Operations

=== Insertion

=== Deletion

=== Balancing

=== Types of Trees

=== Binary Trees

=== Properties

=== Search

=== Sort

=== Other Tree Types

=== Red and Black Trees

=== AVL Trees

=== Tries

=== Other trees

=== Example Questions

=== Finding height of tree

=== Tree longest path

=== Balanced tree

=== Merging trees
