[[DtCI_ch01]]
////
Then, in Ch 1 you could outline details specific to the coding interview. 
* What might the interview look like? 
* What are the interviewers looking for? 
* How can the reader prepare specifically? *What are some real-world examples of what the interview might look like? 

Case studies would be really useful in this chapter! Maybe you could add a case study in a sidebar which walks the reader through an overview.
////

== Preparing for the Coding Interview

If you've looked for a job as a developer anytime over the past 10 years, you've almost certainly been asked to take a coding test.
The very phrase, "coding test," strikes fear into the hearts of developers from Palo Alto to the Passaic.  
If this describes you, fear no longer.
The book in your hands (or on your screen) is your guide to how to take and pass coding tests.
With some time, effort, and energy this book will hopefully help you build the knowledge and skills needed to answer coding interview questions like a pro.  

////
If previous sections move to the preface, here you could add an introduction to this chapter - a brief description of what the interview (specific to coding, i.e. as opposed to a Target interview) consists of, for example.
////


// === Study Plan
// Moved to preface


=== During the Interview

There unfortunately is not a single way in which coding tests are administered by companies.
What you are asked can change from company-to-company, and even from interviewer to interviewer.
You might be put into a room and asked to solve three questions on your own in an hour, or the interviewer might say "Let's solve a problem together" and take you through a team exercise.
The question might be straightforward or it might be designed to bend your brain.  You might be asked to enter your code into a computer or you might be asked to write on a whiteboard.

If it's just you and a coding test and a clock then spend a moment thinking about how to maximize your time.
The questions will be of different difficulties.
Oftentimes you will not be able to answer all of the questions in the time given.
Do you feel more comfortable answering several hard questions or a single easy one?
If it's a group exercise, would you like to spend more time talking or more time coding?

There are a lot of resources online about how to present yourself in interviews from how to write a resume to how to dress to how to speak.
Spend some time looking at these so you're not surprised by what you find once you get into the interview room.

=== Backup Plan

Things don't always go the way we expect, even (especially) when they seem like they will.
The odds are, you won't get the job.
Expect it.
You might know exactly why you didn't get the job or you might have no idea.
Don't take it personally, it really doesn't matter and likely has little to do with you as an individual.
The only thing you can do is regroup, figure out how to improve, and figure out what to do differently the next time.
After you leave the interview, take a moment and reflect.
Write down the questions if you can remember them. 
Go home and look up anything you didn't understand.
Fortify yourself for the next time.
The re-plan, re-apply, and expect to do better the next time!

=== The Importance of Doing the Work

There is no learning without doing.
You can read this book many times over but unless you have a photographic memory, you will have a hard time learning data structures and algorithms without going through the exercises and trying things out for yourself.

It's incredibly important that you sit down in front of a computer and try the things you need to learn from this book.
At the end of most chapters I will give ideas for ways to expand on the concepts that have been covered on your own.
As someone who always skips over these kinds of things, I'm asking you not to skip over these things.
Spend some time with the ideas.
If they're too easy, find a way to modify them to suit your skill level, or find a LeetCode problem that utilizes them.
If they're too hard, break them down into smaller problems that you can solve -- an idea I'll come back to more than once in this book.

I also suggest you "grow before you know," which means working on problems that seem a little more challenging than you can handle.
The more you push yourself, the faster you'll learn.
It's an uncomfortable feeling, and I suggest you get used to it!



