name: deploy-book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: nailing-coding-interview
          auto-activate-base: false

      - name: Initialize and build the book
        shell: bash -l {0}
        run: |
          jupyter-book init
          jupyter-book build --html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
